model_path: /path/tollama-7b
dataset: c4
wbits: 3
quant: ldlq

pre_gptqH: true
pre_rescale: true
pre_proj: true
pre_proj_extra: 1

qfn: 'b'
save_path: /path/to/QuIP/llama-v1.5-7b-w3
CUDA_VISIBLE_DEVICES: "1"